apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend-namespace
spec:
  selector:
    app: backend_mathtraining
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
