apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-namespace
spec:
  selector:
    app: frontend_mathtraining
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP